server:
  port: 8084
spring:
  application:
    name: order-accepted
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/order-accepted
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true