server:
  port: 8088
spring:
  application:
    name: shelf
  datasource:
    password: 'password'
    url: jdbc:postgresql://localhost:5432/ethanol
    username: 'rszumlas'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#        jdbc:
#          batch-size: 5
    show-sql: true