server:
  port: 8087
spring:
  application:
    name: profession
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/profession
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true